linters:
  enable:
    - gofmt
    - goimports
    - stylecheck

issues:
  exclude-dirs:
    - mind-cluster
    - libvnpu
  exclude-rules:
    - path: internal/server/server\.go
      linters:
        - staticcheck
      text: "SA1019:.*deprecated"
