version: "2"

linters:
  enable:
    - asciicheck
    - misspell
    - staticcheck

  exclusions:
    paths:
      - mind-cluster
      - libvnpu

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    paths:
      - mind-cluster
      - libvnpu
