{{- if .Values.config.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.deviceConfigMapName }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "ascend-device-plugin.labels" . | nindent 4 }}
data:
  device-config.yaml: |-
{{- tpl .Values.deviceConfig . | nindent 4 }}
{{- end }}
{{- if .Values.nodeConfigMap.create }}
{{- if .Values.config.create }}
---
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ascend-device-plugin.nodeConfigMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "ascend-device-plugin.labels" . | nindent 4 }}
data:
  node-config.yaml: |-
{{- .Values.nodeConfig | nindent 4 }}
{{- end }}
